export const title = 'WeCle ';

export const keywords = [
  'Wecle updates',
  'Wecle community',
  'Wecle technology',
  'Wecle innovation',
  'Wecle trends',
  'Wecle insights',
  'Wecle reviews',
  'Wecle analysis',
  'Wecle services',
  'Wecle solutions',
  'Wecle benefits',
  'Wecle tips',
  'Wecle best practices',
  'Wecle guide',
  'Wecle resources',
  'Wecle tutorial',
  'Wecle tools',
  'Wecle strategies',
  'Wecle case studies',
  'Wecle updates',
  'Wecle newsfeed',
  'Wecle events',
  'Wecle community engagement',
  'Wecle user experience',
  'Wecle success stories',
  'Wecle challenges',
  'Wecle opportunities',
  'Wecle user guide',
  'Wecle tutorial',
  'Wecle FAQs',
  'Wecle support',
  'Wecle forum',
  'Wecle collaboration',
  'Wecle features',
  'Wecle customization',
  'Wecle security',
  'Wecle data privacy',
  'Wecle user interface',
  'Wecle mobile',
  'Wecle desktop',
  'Wecle benefits',
  'Wecle productivity',
  'Wecle user testimonials',
  'Wecle success tips',
  'Wecle best practices',
  'Wecle case studies',
  'Wecle industry trends',
  'Wecle future',
  'Wecle vision',
  'Wecle mission',
  'Wecle goals',
  'Wecle roadmap',
];

export const description = `
Discover the power of Wecle - your all-in-one platform for innovation and collaboration. Stay informed with the latest updates, insights, and trends. Join our vibrant community, explore user-friendly features, and find tailored solutions. Wecle: Empowering your success with technology, community, and innovation.
`;
