import type { Metadata } from 'next';
import { Quicksand, Source_Serif_4 } from 'next/font/google';
import './globals.css';
import { Navbar } from '@/components/navbar';
import { AuthOverlay } from '@/features/auth';
import QueryProvider from '@/providers/query-provider';
import { getServerSession } from '@/hooks/sessions';
import NextTopLoader from 'nextjs-toploader';

const quick = Quicksand({
  subsets: ['latin'],
  variable: '--quick-sand',
});

const sourceSerif = Source_Serif_4({
  variable: '--source-serif',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={`${quick.variable} ${sourceSerif.variable} font-sans`}>
        <NextTopLoader />
        <QueryProvider>
          <Navbar session={session} />
          <AuthOverlay />
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
