import type { Metadata } from 'next';
import { Quicksand, Source_Serif_4 } from 'next/font/google';
import './globals.css';
import { Navbar } from '@/components/navbar';
import AtomProviders from '@/providers/atom-provider';
import { AuthOverlay } from '@/features/auth';

const quick = Quicksand({
  subsets: ['latin'],
  variable: '--quick-sand',
});

const sourceSerif = Source_Serif_4({
  variable: '--source-serif',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${quick.variable} ${sourceSerif.variable} font-sans`}>
        <AtomProviders>
          <Navbar />
          <AuthOverlay />
          {children}
        </AtomProviders>
      </body>
    </html>
  );
}
