import type { Metadata } from 'next';
import { Quicksand, Source_Serif_4 } from 'next/font/google';
import './globals.css';
import { Navbar } from '@/components/navbar';
import AtomProviders from '@/providers/atom-provider';
import { AuthOverlay } from '@/features/auth';
import QueryProvider from '@/providers/query-provider';
import { getServerSession } from '@/hooks/sessions';

const quick = Quicksand({
  subsets: ['latin'],
  variable: '--quick-sand',
});

const sourceSerif = Source_Serif_4({
  variable: '--source-serif',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={`${quick.variable} ${sourceSerif.variable} font-sans`}>
        <QueryProvider>
          <AtomProviders>
            <Navbar session={session} />
            <AuthOverlay />
            {children}
          </AtomProviders>
        </QueryProvider>
      </body>
    </html>
  );
}
